/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mini_project;
import javax.swing.*;
import java.sql.*;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.Color;
/**
import java.awt.Color;


/**
 *
 * @author MUGKESHANANTH
 */
public class Forgot_Password extends javax.swing.JFrame {
    Connection con;
    Statement st;
    PreparedStatement ps;
    ResultSet rs;
    /**
     * Creates new form new_user
     */
    public Forgot_Password() {
        initComponents();
             try{
                    Class.forName("oracle.jdbc.OracleDriver");
                   // JOptionPane.showMessageDialog(this,"Driver Loaded!");
                    try {                  
                    con = DriverManager.getConnection("jdbc:oracle:thin:@LAPTOP-NQMMIOER:1522:orcl",
                            "scott","tiger");                    
                   // JOptionPane.showMessageDialog(this,"Connected to Oracle database!");
                }
                catch (SQLException ex) {
                    Logger.getLogger(Forgot_Password.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this,ex.getMessage());
                    }
                    }
                    catch(ClassNotFoundException ex){
                    Logger.getLogger(Forgot_Password.class.getName()).log(Level.SEVERE,null, ex);
                    JOptionPane.showMessageDialog(this,ex.getMessage());

                    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        usernamefield = new javax.swing.JTextField();
        retypefield = new javax.swing.JTextField();
        RetypeField = new javax.swing.JLabel();
        Login = new javax.swing.JButton();
        passwordfield = new javax.swing.JTextField();
        PasswordField = new javax.swing.JLabel();
        UsernameField = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mini_project/pharmacy_logo.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 410));

        jPanel4.setBackground(new java.awt.Color(102, 102, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 36)); // NOI18N
        jLabel2.setText("☺️ Welcome ☺️");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 300, 50));

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 24)); // NOI18N
        jLabel3.setText("Login");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernamefield.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        usernamefield.setForeground(new java.awt.Color(153, 153, 153));
        usernamefield.setText("Enter Username"); // NOI18N
        usernamefield.setToolTipText("");
        usernamefield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernamefieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernamefieldFocusLost(evt);
            }
        });
        usernamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernamefieldActionPerformed(evt);
            }
        });
        jPanel5.add(usernamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 150, -1));

        retypefield.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        retypefield.setForeground(new java.awt.Color(153, 153, 153));
        retypefield.setText("retype_Password");
        retypefield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                retypefieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                retypefieldFocusLost(evt);
            }
        });
        jPanel5.add(retypefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 110, -1));

        RetypeField.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        RetypeField.setText("retype_password :");
        jPanel5.add(RetypeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));

        Login.setBackground(new java.awt.Color(153, 255, 153));
        Login.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        Login.setText("Login");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        jPanel5.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 90, -1));

        passwordfield.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        passwordfield.setForeground(new java.awt.Color(153, 153, 153));
        passwordfield.setText("Enter Password");
        passwordfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordfieldFocusLost(evt);
            }
        });
        jPanel5.add(passwordfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 150, -1));

        PasswordField.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        PasswordField.setText("Password :");
        jPanel5.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        UsernameField.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        UsernameField.setText("User name :");
        jPanel5.add(UsernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mini_project/rainbows.jpg"))); // NOI18N
        jLabel6.setText("jLabel3");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 300, 250));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 290, 250));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 330, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernamefieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernamefieldFocusGained
        // TODO add your handling code here:
        if(usernamefield.getText().equals("Enter Username"))
        {
            usernamefield.setText("");
            usernamefield.setForeground(new Color(153,153,153));

        }
    }//GEN-LAST:event_usernamefieldFocusGained

    private void usernamefieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernamefieldFocusLost
        // TODO add your handling code here:
        if(usernamefield.getText().equals(""))
        {
            usernamefield.setText("Enter Username");
            usernamefield.setForeground(new Color(153,153,153));

        }

    }//GEN-LAST:event_usernamefieldFocusLost

    private void passwordfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordfieldFocusGained
        // TODO add your handling code here:
        if(passwordfield.getText().equals("Enter Password"))
        {
            passwordfield.setText("");
            passwordfield.setForeground(new Color(153,153,153));

        }
    }//GEN-LAST:event_passwordfieldFocusGained

    private void passwordfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordfieldFocusLost
        // TODO add your handling code here:
        if(passwordfield.getText().equals(""))
        {
            passwordfield.setText("Enter Password");
            passwordfield.setForeground(new Color(153,153,153));

        }
    }//GEN-LAST:event_passwordfieldFocusLost

    private void retypefieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_retypefieldFocusGained
        // TODO add your handling code here:
        if(retypefield.getText().equals("retype_Password"))
        {
            retypefield.setText("");
            retypefield.setForeground(new Color(153,153,153));

        }
    }//GEN-LAST:event_retypefieldFocusGained

    private void retypefieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_retypefieldFocusLost
        // TODO add your handling code here:
         if(retypefield.getText().equals(""))
        {
            retypefield.setText("retype_Password");
            retypefield.setForeground(new Color(153,153,153));

        }
    }//GEN-LAST:event_retypefieldFocusLost

    private boolean updateEmployees(String username, String retypepassword) {
    PreparedStatement ps = null;
    try {
        String query = "UPDATE Employees SET password = ? WHERE employee_name = ?";
        ps = con.prepareStatement(query);
        ps.setString(1, retypepassword);
        ps.setString(2, username);
        System.out.println(ps.toString());
        int rowsAffected = ps.executeUpdate();
        System.out.println("Rows affected: " + rowsAffected);
        
        return rowsAffected > 0;
    } catch (SQLException ex) {
        Logger.getLogger(Forgot_Password.class.getName()).log(Level.SEVERE,null,0);
        JOptionPane.showMessageDialog(this, ex.getMessage());
        return false;
    } finally {
        try {
            if (ps != null) {
                ps.close();
            }
        } catch (SQLException ex) {
            Logger.getLogger(Forgot_Password.class.getName()).log(Level.SEVERE,null,0);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
}
      
 
    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
                                            
    String username = usernamefield.getText().trim();
    String typedpassword = passwordfield.getText().trim();
    String retypepassword = retypefield.getText().trim();
    
    // Ensure passwords match before attempting to update
    if (!typedpassword.equals(retypepassword)) {
        JOptionPane.showMessageDialog(this, "Passwords do not match. Please retype your password.");
        return;
    }

    if (updateEmployees(username, retypepassword)) {
        JOptionPane.showMessageDialog(this, "Your password updated successfully!");
        this.dispose(); // Close the current window

        // Open the homepage
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    } else {
        JOptionPane.showMessageDialog(this, "Error in resetting the password. Please try again.");
    }


    }//GEN-LAST:event_LoginActionPerformed

    private void usernamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernamefieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forgot_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forgot_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forgot_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forgot_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forgot_Password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login;
    private javax.swing.JLabel PasswordField;
    private javax.swing.JLabel RetypeField;
    private javax.swing.JLabel UsernameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField passwordfield;
    private javax.swing.JTextField retypefield;
    private javax.swing.JTextField usernamefield;
    // End of variables declaration//GEN-END:variables
}
