/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mini_project;
import javax.swing.*;
import java.sql.*;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.Color;
/**
 *
 * @author MUGKESHANANTH
 */
public class Profile extends javax.swing.JFrame {
    Connection con;
    Statement st;
    PreparedStatement ps;
    ResultSet rs;
    /**
     * Creates new form Profile
     */
    public Profile() {
        initComponents();
            try{
                    Class.forName("oracle.jdbc.OracleDriver");
                    //JOptionPane.showMessageDialog(this,"Driver Loaded!");
                    try {                  
                   con = DriverManager.getConnection("jdbc:oracle:thin:@LAPTOP-NQMMIOER:1522:orcl",
                            "scott","tiger");                     
                   // JOptionPane.showMessageDialog(this,"Connected to Oracle database!");
                }
                catch (SQLException ex) {
                    Logger.getLogger(Profile.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this,ex.getMessage());
                    }
                    }
                    catch(ClassNotFoundException ex){
                    Logger.getLogger(Profile.class.getName()).log(Level.SEVERE,null, ex);
                    JOptionPane.showMessageDialog(this,ex.getMessage());

                    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        idfield = new javax.swing.JTextField();
        namefield = new javax.swing.JTextField();
        mailfield = new javax.swing.JTextField();
        nofield = new javax.swing.JTextField();
        dobfield = new javax.swing.JTextField();
        positionfield = new javax.swing.JTextField();
        addressfield = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        pincodefield = new javax.swing.JTextField();
        Backhomebutton = new javax.swing.JButton();
        Fetch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255,180));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel2.setText("User Profile");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel3.setText("Employee_id :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 69, -1, 26));

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel4.setText("Name :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, 30));

        jLabel5.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel5.setText("E-mail :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 157, -1, 26));

        jLabel6.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel6.setText(" Phone_no :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 195, -1, 26));

        jLabel7.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel7.setText("DOB :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 235, -1, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel8.setText("Position :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 275, -1, -1));

        jLabel10.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel10.setText("Address :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        idfield.setText("1");
        idfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idfieldActionPerformed(evt);
            }
        });
        jPanel2.add(idfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 72, 169, -1));

        namefield.setText("Lenkesh\n");
        jPanel2.add(namefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 113, 169, -1));

        mailfield.setText("lenkeshMessi@gmail.com");
        jPanel2.add(mailfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 160, 169, -1));

        nofield.setText("737237237273");
        jPanel2.add(nofield, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 198, 169, -1));

        dobfield.setText("28/Feb/2005");
        jPanel2.add(dobfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 233, 169, -1));

        positionfield.setText("Sales Exec");
        jPanel2.add(positionfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 273, 169, -1));

        addressfield.setText("#3, Gojo Street,Ameerjan,Chennai-600066");
        jPanel2.add(addressfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 169, 30));

        jLabel12.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel12.setText("Pincode :");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        pincodefield.setText("600066");
        jPanel2.add(pincodefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 160, -1));

        Backhomebutton.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        Backhomebutton.setText("Back");
        Backhomebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackhomebuttonActionPerformed(evt);
            }
        });
        jPanel2.add(Backhomebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, -1, -1));

        Fetch.setText("Fetch");
        Fetch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FetchActionPerformed(evt);
            }
        });
        jPanel2.add(Fetch, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 340, 460));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mini_project/newuserbb.jpeg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 505));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackhomebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackhomebuttonActionPerformed
        // TODO add your handling code here:
                  this.dispose();

            // Open the homepage
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new Homepage().setVisible(true);
                }
            });
    }//GEN-LAST:event_BackhomebuttonActionPerformed

    private void idfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idfieldActionPerformed

    private void FetchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FetchActionPerformed
        // TODO add your handling code here:
                // Action performed when Fetch button is clicked
        Connection con = null;
        PreparedStatement ps = null;
        ResultSet rs = null;

        try {
            // Establish database connection
            con = DriverManager.getConnection("jdbc:oracle:thin:@LAPTOP-NQMMIOER:1522:orcl",
                            "scott","tiger");                    

            // SQL query to fetch employee details based on employee_id
            String query = "SELECT * FROM Employees WHERE employee_id = ?";
            ps = con.prepareStatement(query);

            // Set employee_id parameter from idfield
            int employeeId = Integer.parseInt(idfield.getText().trim());
            ps.setInt(1, employeeId);

            // Execute the query
            rs = ps.executeQuery();

            // Check if any results found
            if (rs.next()) {
                // Retrieve employee details from ResultSet
                String employeeName = rs.getString("employee_name");
                String position = rs.getString("position");
                String email = rs.getString("employee_email");
                String phone = rs.getString("employee_phone");
                //String commission = rs.getString("commission");
                String dob = rs.getString("DOB"); // Assuming dobfield is a JTextField for date of birth
                String address = rs.getString("address");
                int pincode = rs.getInt("pincode");

                // Populate retrieved data into text fields
                namefield.setText(employeeName);
                positionfield.setText(position);
                mailfield.setText(email);
                nofield.setText(phone);
                //commissionfield.setText(commission);
                dobfield.setText(dob); // Format the date as needed
                addressfield.setText(address);
                pincodefield.setText(String.valueOf(pincode));
            } else {
                JOptionPane.showMessageDialog(null, "Employee not found with ID: " + employeeId, "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error fetching employee details: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            // Close resources in finally block
            try {
                if (rs != null) rs.close();
                if (ps != null) ps.close();
                if (con != null) con.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_FetchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backhomebutton;
    private javax.swing.JButton Fetch;
    private javax.swing.JTextField addressfield;
    private javax.swing.JTextField dobfield;
    private javax.swing.JTextField idfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField mailfield;
    private javax.swing.JTextField namefield;
    private javax.swing.JTextField nofield;
    private javax.swing.JTextField pincodefield;
    private javax.swing.JTextField positionfield;
    // End of variables declaration//GEN-END:variables
}
