 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mini_project;

import javax.swing.*;
import java.sql.*;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author MUGKESHANANTH
 */
public class Return extends javax.swing.JFrame {
    Connection con;
    Statement st;
    PreparedStatement ps;
    ResultSet rs;
    /**
     * Creates new form Return
     */
    public Return() {
        initComponents();
            try {
                    Class.forName("oracle.jdbc.OracleDriver");
                    //JOptionPane.showMessageDialog(this,"Driver Loaded!");
                    try {                  
                    con = DriverManager.getConnection("jdbc:oracle:thin:@LAPTOP-NQMMIOER:1522:orcl",
                            "scott","tiger");                     
                   // JOptionPane.showMessageDialog(this,"Connected to Oracle database!");
                }
                catch (SQLException ex) {
                    Logger.getLogger(Return.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this,ex.getMessage());
                    }
                    }
                    catch(ClassNotFoundException ex){
                    Logger.getLogger(Return.class.getName()).log(Level.SEVERE,null, ex);
                    JOptionPane.showMessageDialog(this,ex.getMessage());

                    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LoadButton = new javax.swing.JButton();
        MedicineList = new javax.swing.JComboBox<>();
        QuantityList = new javax.swing.JSpinner();
        ReturnListButton = new javax.swing.JButton();
        ListViewButton = new javax.swing.JButton();
        BackInventoryButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoadButton.setText("jButton1");
        LoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadButtonActionPerformed(evt);
            }
        });
        jPanel1.add(LoadButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 20, 30));

        jPanel1.add(MedicineList, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 150, 30));
        jPanel1.add(QuantityList, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 80, 30));

        ReturnListButton.setBackground(new java.awt.Color(153, 255, 255));
        ReturnListButton.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        ReturnListButton.setForeground(new java.awt.Color(51, 51, 0));
        ReturnListButton.setText("Add to Return list");
        ReturnListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnListButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ReturnListButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 200, -1));

        ListViewButton.setBackground(new java.awt.Color(153, 255, 255));
        ListViewButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ListViewButton.setText("Go to List");
        ListViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListViewButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ListViewButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 140, -1));

        BackInventoryButton.setBackground(new java.awt.Color(255, 51, 51));
        BackInventoryButton.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        BackInventoryButton.setText("Back");
        BackInventoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackInventoryButtonActionPerformed(evt);
            }
        });
        jPanel1.add(BackInventoryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 90, 30));

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 51));
        jLabel4.setText("Pharamcy Return");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel1.setText("Quantity :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel3.setText("Medicine :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mini_project/bb.jpg"))); // NOI18N
        jLabel2.setToolTipText("");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel2.setPreferredSize(new java.awt.Dimension(700, 600));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReturnListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnListButtonActionPerformed
        // TODO add your handling code here:
//        
//    Connection con = null;
//    PreparedStatement ps = null;
//    ResultSet rs = null;
//    String selectedMedicineName = (String) MedicineList.getSelectedItem();
//    int quantity = (Integer) QuantityList.getValue(); // Assuming quantitylist is a JSpinner
//
//    if (selectedMedicineName != null && quantity > 0) {
//        MedicineItem selectedMedicine = null;
//        
//        // Find the MedicineItem with the selected name
//        for (MedicineItem item : medicineItems) {
//            if (item.name.equals(selectedMedicineName)) {
//                selectedMedicine = item;
//                break;
//            }
//        }
//
//        if (selectedMedicine != null) { 
//
//   String sql = "INSERT INTO Returns (return_id, sale_id, return_date, return_reason, return_quantity) VALUES (?, ?, ?, ?, ?)";
//
//            try {
//                con = DriverManager.getConnection("jdbc:oracle:thin:@LAPTOP-NQMMIOER:1522:orcl", "scott", "tiger");
//                ps = con.prepareStatement(sql);
//                
//                // Generate a random return ID
//                int returnId = new java.util.Random().nextInt(900000) + 100000; // Generate a random 6-digit number
//                
//                // Generate a random return reason
//                String[] returnReasons = {"Expired", "Incorrect Order", "Failed to Seal", "Others"};
//                String returnReason = returnReasons[new java.util.Random().nextInt(returnReasons.length)];
//                
//                ps.setInt(1, returnId);
//                ps.setNull(2, java.sql.Types.INTEGER); // sale_id is null
//                ps.setDate(3, new java.sql.Date(System.currentTimeMillis())); // Use current date
//                ps.setString(4, returnReason);
//                ps.setInt(5, quantity);
//                
//                int rowsInserted = ps.executeUpdate();
//                if (rowsInserted > 0) {
//                    JOptionPane.showMessageDialog(null, "Medicine added to return successfully!");
//                }
//            } catch (SQLException e) {
//                e.printStackTrace();
//                JOptionPane.showMessageDialog(null, "Error adding medicine to return: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
//            } finally {
//                try {
//                    if (ps != null) ps.close();
//                } catch (SQLException e) {
//                    e.printStackTrace();
//                }
//            }
//        } else {
//            JOptionPane.showMessageDialog(null, "Selected medicine not found.", "Error", JOptionPane.ERROR_MESSAGE);
//        }
//    } else {
//        JOptionPane.showMessageDialog(null, "Please select a medicine and enter a valid quantity.", "Warning", JOptionPane.WARNING_MESSAGE);
//    }
    //Connection con = null;
    PreparedStatement psReturns = null;
    PreparedStatement psReturnDetails = null;
    String selectedMedicineName = (String) MedicineList.getSelectedItem();
    int quantity = (Integer) QuantityList.getValue(); // Assuming quantitylist is a JSpinner

    if (selectedMedicineName != null && quantity > 0) {
        MedicineItem selectedMedicine = null;
        
        // Find the MedicineItem with the selected name
        for (MedicineItem item : medicineItems) {
            if (item.name.equals(selectedMedicineName)) {
                selectedMedicine = item;
                break;
            }
        }

        if (selectedMedicine != null) { 
            String sqlReturns = "INSERT INTO Returns (return_id, sale_id, return_date, return_reason, return_quantity) VALUES (?, ?, ?, ?, ?)";
            String sqlReturnDetails = "INSERT INTO ReturnDetails (return_id, medicine_name, return_reason, return_quantity, return_date) VALUES (?, ?, ?, ?, ?)";
            
            try {
                con = DriverManager.getConnection("jdbc:oracle:thin:@LAPTOP-NQMMIOER:1522:orcl", "scott", "tiger");

                // Insert into Returns table
                psReturns = con.prepareStatement(sqlReturns);
                
                // Generate a random return ID
                int returnId = new java.util.Random().nextInt(900000) + 100000; // Generate a random 6-digit number
                
                // Generate a random return reason
                String[] returnReasons = {"Expired", "Incorrect Order", "Failed to Seal", "Others"};
                String returnReason = returnReasons[new java.util.Random().nextInt(returnReasons.length)];
                
                psReturns.setInt(1, returnId);
                psReturns.setNull(2, java.sql.Types.INTEGER); // sale_id is null
                psReturns.setDate(3, new java.sql.Date(System.currentTimeMillis())); // Use current date
                psReturns.setString(4, returnReason);
                psReturns.setInt(5, quantity);
                
                int rowsInsertedReturns = psReturns.executeUpdate();

                if (rowsInsertedReturns > 0) {
                    // Insert into ReturnDetails table
                    psReturnDetails = con.prepareStatement(sqlReturnDetails);
                    psReturnDetails.setInt(1, returnId);
                    psReturnDetails.setString(2, selectedMedicineName);
                    psReturnDetails.setString(3, returnReason);
                    psReturnDetails.setInt(4, quantity);
                    psReturnDetails.setDate(5, new java.sql.Date(System.currentTimeMillis())); // Use current date
                    
                    int rowsInsertedReturnDetails = psReturnDetails.executeUpdate();

                    if (rowsInsertedReturnDetails > 0) {
                        JOptionPane.showMessageDialog(null, "Medicine added to return successfully!");
                    }
                }
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error adding medicine to return: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            } finally {
                try {
                    if (psReturns != null) psReturns.close();
                    if (psReturnDetails != null) psReturnDetails.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selected medicine not found.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(null, "Please select a medicine and enter a valid quantity.", "Warning", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_ReturnListButtonActionPerformed

    
    private void ListViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListViewButtonActionPerformed
        // TODO add your handling code here:
                  this.dispose();

            // Open the homepage
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new Return_cart().setVisible(true);
                }
            });
    }//GEN-LAST:event_ListViewButtonActionPerformed

    private void BackInventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackInventoryButtonActionPerformed
        // TODO add your handling code here:
                  this.dispose();

            // Open the homepage
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new Inventory().setVisible(true);
                }
            });
    }//GEN-LAST:event_BackInventoryButtonActionPerformed

    private List<MedicineItem> medicineItems = new ArrayList<>();
    private void LoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadButtonActionPerformed
        // TODO add your handling code here:
        
    Connection con = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    

    try {
        // Establish the database connection
        System.out.println("Establishing database connection...");
        con = DriverManager.getConnection("jdbc:oracle:thin:@LAPTOP-NQMMIOER:1522:orcl", "scott", "tiger");
        System.out.println("Database connection established.");

        // Create the SQL query to retrieve medicine items
        String query = "SELECT medicine_id, name FROM Medicine";

        // Prepare the statement
        System.out.println("Preparing SQL statement...");
        ps = con.prepareStatement(query);

        // Execute the query
        System.out.println("Executing query to retrieve medicine items...");
        rs = ps.executeQuery();

        // Iterate over the result set and append medicine items to the list
        System.out.println("Processing result set...");
        while (rs.next()) {
            int medicineId = rs.getInt("medicine_id");
            String name = rs.getString("name");
            MedicineItem medicineItem = new MedicineItem(medicineId, name);
            medicineItems.add(medicineItem);
        }
        System.out.println("Medicine items retrieved: " + medicineItems);

        // Remove all existing items in the combo box
        System.out.println("Clearing existing items in the combo box...");
        MedicineList.removeAllItems();

        // Add the retrieved medicine items to the combo box
        System.out.println("Adding medicine items to the combo box...");
        for (MedicineItem item : medicineItems) {
            MedicineList.addItem(item.name);
        }

    } catch (SQLException ex) {
        System.out.println("SQLException: " + ex.getMessage());
        ex.printStackTrace();
    } finally {
        // Close resources
        try {
            if (rs != null) rs.close();
            if (ps != null) ps.close();
            System.out.println("Resources closed after first query.");
        } catch (SQLException ex) {
            System.out.println("SQLException during resource cleanup: " + ex.getMessage());
            ex.printStackTrace();
        }
    }


    }//GEN-LAST:event_LoadButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Return().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackInventoryButton;
    private javax.swing.JButton ListViewButton;
    private javax.swing.JButton LoadButton;
    private javax.swing.JComboBox<String> MedicineList;
    private javax.swing.JSpinner QuantityList;
    private javax.swing.JButton ReturnListButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
